<?php
    $apikey = "rzp_test_1oOaHeacEoqqX2";
?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>

<form action="index.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amount']*100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(100,1000).'END'; ?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="The Rental Hub Pvt. Ltd."
    data-description="Get your Dream Home on Rent now!"
    data-image="https://i.pinimg.com/originals/24/a9/a2/24a9a23b35abe862d872638b5ed65a94.jpg"
    data-prefill.name="<?php echo $_POST['user_name']; ?>"
    data-prefill.email="<?php echo $_POST['user_email']; ?>"
    data-theme.color="#016450"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>


<style>
    .razorpay-payment-button{
        display: none;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $('.razorpay-payment-button').click();
    });
</script>